"""init

Revision ID: fc214fcf61e3
Revises: 
Create Date: 2026-05-30 07:55:17.443025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc214fcf61e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('autor', sa.String(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('rfid_tag', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('disponivel', 'emprestado', 'inventario', 'perdido', name='book_estado'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_books_estado'), 'books', ['estado'], unique=False)
    op.create_index(op.f('ix_books_rfid_tag'), 'books', ['rfid_tag'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('aluno', 'vigilante', 'admin', name='user_role'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('config',
    sa.Column('chave', sa.Text(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('movimentacao_livro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('livro_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('emprestimo', 'devolucao', 'rfid_lido', 'inventario', 'cadastro', name='movimentacao_tipo'), nullable=False),
    sa.Column('detalhes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacao_livro_livro_id'), 'movimentacao_livro', ['livro_id'], unique=False)
    op.create_index(op.f('ix_movimentacao_livro_timestamp'), 'movimentacao_livro', ['timestamp'], unique=False)
    op.create_index(op.f('ix_movimentacao_livro_tipo'), 'movimentacao_livro', ['tipo'], unique=False)
    op.create_table('sessao_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('em_andamento', 'finalizado', 'cancelado', name='inventario_estado'), nullable=False),
    sa.Column('iniciado_por', sa.UUID(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cadastrado', sa.Integer(), nullable=True),
    sa.Column('total_lido', sa.Integer(), nullable=True),
    sa.Column('total_furos', sa.Integer(), nullable=True),
    sa.Column('relatorio', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['iniciado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('aguardando_aprovacao', 'ativa', 'encerrada', 'expirada', 'rejeitada', name='session_estado'), nullable=False),
    sa.Column('tempo_estimado_min', sa.Integer(), nullable=False),
    sa.Column('motivo_rejeicao', sa.Text(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('livro_retirado_id', sa.UUID(), nullable=True),
    sa.Column('aprovada_por', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprovada_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['livro_retirado_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_estado'), 'sessions', ['estado'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('alertas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('saida_sem_aprovacao', 'livro_sumido', 'rfid_desconhecido', 'webcam_offline', 'sessao_expirada', name='alerta_tipo'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('livro_id', sa.UUID(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolvido_por', sa.UUID(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['resolvido_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_resolvido'), 'alertas', ['resolvido'], unique=False)
    op.create_index(op.f('ix_alertas_tipo'), 'alertas', ['tipo'], unique=False)
    op.create_table('item_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventario_id', sa.UUID(), nullable=False),
    sa.Column('livro_id', sa.UUID(), nullable=False),
    sa.Column('rfid_tag', sa.String(), nullable=False),
    sa.Column('lido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventario_id'], ['sessao_inventario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['livro_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_inventario_inventario_id'), 'item_inventario', ['inventario_id'], unique=False)
    op.create_index(op.f('ix_item_inventario_livro_id'), 'item_inventario', ['livro_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('dias_prazo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ativo', 'devolvido', 'atrasado', name='loan_estado'), nullable=False),
    sa.Column('data_emprestimo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_prevista_devolucao', sa.Date(), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_book_id'), 'loans', ['book_id'], unique=False)
    op.create_index(op.f('ix_loans_estado'), 'loans', ['estado'], unique=False)
    op.create_index(op.f('ix_loans_user_id'), 'loans', ['user_id'], unique=False)
    op.create_table('log_acesso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('acao', sa.Enum('abrir', 'fechar', name='fechadura_acao'), nullable=False),
    sa.Column('origem', sa.Enum('sistema', 'admin', 'timeout', name='fechadura_origem'), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_acesso_session_id'), 'log_acesso', ['session_id'], unique=False)
    op.create_index(op.f('ix_log_acesso_timestamp'), 'log_acesso', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_acesso_timestamp'), table_name='log_acesso')
    op.drop_index(op.f('ix_log_acesso_session_id'), table_name='log_acesso')
    op.drop_table('log_acesso')
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_estado'), table_name='loans')
    op.drop_index(op.f('ix_loans_book_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_item_inventario_livro_id'), table_name='item_inventario')
    op.drop_index(op.f('ix_item_inventario_inventario_id'), table_name='item_inventario')
    op.drop_table('item_inventario')
    op.drop_index(op.f('ix_alertas_tipo'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_resolvido'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_estado'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('sessao_inventario')
    op.drop_index(op.f('ix_movimentacao_livro_tipo'), table_name='movimentacao_livro')
    op.drop_index(op.f('ix_movimentacao_livro_timestamp'), table_name='movimentacao_livro')
    op.drop_index(op.f('ix_movimentacao_livro_livro_id'), table_name='movimentacao_livro')
    op.drop_table('movimentacao_livro')
    op.drop_table('config')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_rfid_tag'), table_name='books')
    op.drop_index(op.f('ix_books_estado'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
